# file: .github/workflows/hexlet-ci-app.yml
name: setup-&-test
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      # run – произвольная bash-команда
      - run: make setup
      # Запускаем тесты
      - run: make test
      # Запускаем линтер
      - run: make lint
